using System.IO;
using UnityEditor;
using UnityEngine;

namespace ChopChop.Editor
{
    /// <summary>
    /// Builds the placeholder trunk: a plain brown cylinder standing in for a tree.
    ///
    /// Deliberately not an imported model. Judging forest density through the acacia pack
    /// meant judging its canopies at the same time, and the two are not separable by eye —
    /// a bare trunk at a known diameter is an instrument rather than a decoration. It is
    /// also the right shape for what this forest is meant to be: Oregon old growth is
    /// tall straight columns, not spreading crowns.
    ///
    /// Generated by a menu item rather than committed as an opaque binary so the numbers
    /// that define it stay legible and adjustable. Regenerating overwrites in place, which
    /// keeps every reference to it intact.
    /// </summary>
    public static class PlaceholderTrunkGenerator
    {
        private const string Folder = "Assets/_Project/Runtime/Biomes/Placeholder";
        private const string MeshPath = Folder + "/PlaceholderTrunk.asset";
        private const string MaterialPath = Folder + "/PlaceholderBark.mat";

        /// <summary>Diameter in metres at scale 1. A mature Douglas fir is around this.</summary>
        private const float Diameter = 0.75f;

        /// <summary>
        /// Height in metres at scale 1. Short for real old growth, which runs past 60m,
        /// but tall enough that the canopy leaves the frame and the forest closes over you.
        /// </summary>
        private const float Height = 30f;

        /// <summary>
        /// Radial segments. 12 is round enough at the distance trunks are actually read
        /// from, and this mesh is drawn tens of thousands of times per frame.
        /// </summary>
        private const int Sides = 12;

        [MenuItem("ChopChop/Regenerate Placeholder Trunk")]
        public static void Generate()
        {
            Directory.CreateDirectory(Folder);

            Mesh mesh = BuildMesh();
            WriteAsset(mesh, MeshPath);

            Material material = BuildMaterial();
            WriteAsset(material, MaterialPath);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[Placeholder] Trunk rebuilt: {Diameter}m across, {Height}m tall, " +
                      $"{mesh.triangles.Length / 3} triangles.");
        }

        /// <summary>
        /// Overwrites the existing asset's contents rather than replacing the asset, so
        /// the GUID survives and every biome still points at the same trunk.
        /// </summary>
        private static void WriteAsset<T>(T built, string path) where T : Object
        {
            T existing = AssetDatabase.LoadAssetAtPath<T>(path);

            if (existing == null)
            {
                AssetDatabase.CreateAsset(built, path);
                return;
            }

            EditorUtility.CopySerialized(built, existing);
            EditorUtility.SetDirty(existing);
            Object.DestroyImmediate(built);
        }

        private static Mesh BuildMesh()
        {
            float radius = Diameter * 0.5f;

            /* The seam is duplicated: the vertex at 0 degrees and the one at 360 share a
             * position but need different U coordinates, and welding them wraps the
             * texture backwards across one face. */
            int ring = Sides + 1;

            var vertices = new Vector3[ring * 2 + Sides + 1];
            var normals = new Vector3[vertices.Length];
            var uvs = new Vector2[vertices.Length];

            for (int i = 0; i < ring; i++)
            {
                float t = i / (float)Sides;
                float angle = t * Mathf.PI * 2f;
                Vector3 outward = new(Mathf.Sin(angle), 0f, Mathf.Cos(angle));

                vertices[i] = outward * radius;
                vertices[i + ring] = outward * radius + Vector3.up * Height;

                // Radial, so 12 flat faces shade as a round trunk.
                normals[i] = outward;
                normals[i + ring] = outward;

                // Roughly square texels on a 30m trunk, for whatever bark lands here later.
                uvs[i] = new Vector2(t * Mathf.PI * Diameter, 0f);
                uvs[i + ring] = new Vector2(t * Mathf.PI * Diameter, Height);
            }

            /* Top cap only. The base is against the ground and never seen, and this mesh
             * is instanced heavily enough that unseen triangles are worth not having. */
            int capCentre = ring * 2;
            vertices[capCentre] = Vector3.up * Height;
            normals[capCentre] = Vector3.up;
            uvs[capCentre] = new Vector2(0.5f, 0.5f);

            for (int i = 0; i < Sides; i++)
            {
                float angle = i / (float)Sides * Mathf.PI * 2f;
                Vector3 outward = new(Mathf.Sin(angle), 0f, Mathf.Cos(angle));

                vertices[capCentre + 1 + i] = outward * radius + Vector3.up * Height;
                normals[capCentre + 1 + i] = Vector3.up;
                uvs[capCentre + 1 + i] = new Vector2(outward.x * 0.5f + 0.5f, outward.z * 0.5f + 0.5f);
            }

            var triangles = new int[Sides * 6 + Sides * 3];
            int t2 = 0;

            for (int i = 0; i < Sides; i++)
            {
                int bottom = i;
                int top = i + ring;

                triangles[t2++] = bottom;
                triangles[t2++] = top;
                triangles[t2++] = bottom + 1;

                triangles[t2++] = bottom + 1;
                triangles[t2++] = top;
                triangles[t2++] = top + 1;
            }

            for (int i = 0; i < Sides; i++)
            {
                triangles[t2++] = capCentre;
                triangles[t2++] = capCentre + 1 + (i + 1) % Sides;
                triangles[t2++] = capCentre + 1 + i;
            }

            Mesh mesh = new()
            {
                name = "PlaceholderTrunk",
                vertices = vertices,
                normals = normals,
                uv = uvs,
                triangles = triangles,
            };

            mesh.RecalculateBounds();
            mesh.RecalculateTangents();

            return mesh;
        }

        private static Material BuildMaterial()
        {
            Shader shader = Shader.Find("Universal Render Pipeline/Lit");

            if (shader == null)
            {
                Debug.LogError("[Placeholder] URP/Lit not found. Built-in shaders render magenta under URP.");
                shader = Shader.Find("Standard");
            }

            Material material = new(shader) { name = "PlaceholderBark" };

            material.SetColor("_BaseColor", new Color(0.24f, 0.16f, 0.11f));
            material.SetFloat("_Smoothness", 0.05f);
            material.SetFloat("_Metallic", 0f);

            /* Without this every trunk is its own draw call and the forest costs thousands
             * of them. Graphics.RenderMeshInstanced silently gives up the batching rather
             * than warning, so this is easy to lose and hard to notice. */
            material.enableInstancing = true;

            return material;
        }
    }
}
